#cloud-config
package_update: true

packages:
  - collectd

write_files:
  - path: /tmp/crank_setup-crank.sh
    #owner: "ubuntu:ubuntu"
    permissions: '0755'
    content: |
      #!/usr/bin/env bash
      wget https://dot.net/v1/dotnet-install.sh
      chmod a+x dotnet-install.sh
      ./dotnet-install.sh -InstallDir $HOME/dnet7 -Channel 7.0
      PATH=$HOME/dnet7:$PATH dotnet tool install -g Microsoft.Crank.Agent --version "0.2.0-*"
      DOTNET_ROOT=$HOME/dnet7 PATH=$HOME/.dotnet/tools:$PATH crank-agent
  # - path: /tmp/crank_etc_collectd_collectd.conf
  #   #owner: "ubuntu:ubuntu"
  #   permissions: '0755'
  #   content: |
  #     Interval 10

  #     LoadPlugin syslog
  #     LoadPlugin cpu
  #     LoadPlugin csv
  #     LoadPlugin ethstat
  #     LoadPlugin interface
  #     LoadPlugin ipc
  #     LoadPlugin load
  #     LoadPlugin memory
  #     LoadPlugin cpufreq
  #     LoadPlugin "aggregation"

  #     <Plugin cpu>
  #       ReportByCpu true
  #       ValuesPercentage false
  #     </Plugin>
  #     <Plugin csv>
  #       DataDir "/var/lib/collectd/csv"
  #       StoreRates true
  #     </Plugin>
  #     <Plugin ethstat>
  #       Interface "/^eth[0-9]?$/"
  #       Interface "/^ens[0-9]?$/"
  #       Map "rx_csum_offload_errors" "if_rx_errors" "checksum_offload"
  #       Map "multicast" "if_multicast"
  #       MappedOnly false
  #     </Plugin>
  #     <Plugin interface>
  #       Interface "/^eth/"
  #       Interface "/^enp/"
  #       IgnoreSelected false
  #     </Plugin>
  #     <Plugin load>
  #       ReportRelative true
  #     </Plugin>
  #     <Plugin "aggregation">
  #       <Aggregation>
  #               Plugin "cpu"
  #               Type "cpu"
  #               GroupBy "Host"
  #               GroupBy "TypeInstance"
  #               CalculateAverage true
  #       </Aggregation>
  #     </Plugin>