#cloud-config
package_update: true

packages:
  - collectd

write_files:
  - path: /tmp/crank_setup-crank.sh
    #owner: "ubuntu:ubuntu"
    permissions: '0755'
    content: |
      #!/usr/bin/env bash
      wget https://dot.net/v1/dotnet-install.sh
      chmod a+x dotnet-install.sh
      ./dotnet-install.sh -InstallDir $HOME/dnet7 -Channel 7.0
      PATH=$HOME/dnet7:$PATH dotnet tool install -g Microsoft.Crank.Agent --version "0.2.0-*"
      DOTNET_ROOT=$HOME/dnet7 PATH=$HOME/.dotnet/tools:$PATH crank-agent
